import { createEnvRecord } from "./env";

const ENV_VARS = [
  "CLERK_WEBHOOK_SECRET",
  "CLERK_JWT_ISSUER_DOMAIN",
  "NEXT_PUBLIC_STRIPE_TIER_1_PRICEID",
  "NEXT_PUBLIC_STRIPE_TIER_2_PRICEID",
  "NEXT_PUBLIC_STRIPE_TIER_3_PRICEID",
  "NEXT_PUBLIC_STRIPE_TIER_1_CREDITS",
  "NEXT_PUBLIC_STRIPE_TIER_2_CREDITS",
  "NEXT_PUBLIC_STRIPE_TIER_3_CREDITS",
  "STRIPE_KEY",
  "STRIPE_WEBHOOKS_SECRET",
  "SITE_URL",
  "DEFAULT_CREDITS",
  "NEXT_PUBLIC_UPLOAD_SIZE_LIMIT",
] as const;

export const convexEnv = createEnvRecord(ENV_VARS);
