import { createEnvRecord } from "./env";

const ENV_VARS = [
  "NEXT_PUBLIC_STRIPE_TIER_1_PRICEID",
  "NEXT_PUBLIC_STRIPE_TIER_2_PRICEID",
  "NEXT_PUBLIC_STRIPE_TIER_3_PRICEID",
  "NEXT_PUBLIC_STRIPE_TIER_1_CREDITS",
  "NEXT_PUBLIC_STRIPE_TIER_2_CREDITS",
  "NEXT_PUBLIC_STRIPE_TIER_3_CREDITS",
  "STRIPE_KEY",
  "STRIPE_WEBHOOKS_SECRET",
  "SITE_URL",
  "DEFAULT_CREDITS",
  "NEXT_PUBLIC_UPLOAD_SIZE_LIMIT",
  "AUTH_GOOGLE_ID",
  "AUTH_GOOGLE_SECRET",
  "CONVEX_SITE_URL",
] as const;

export const convexEnv = createEnvRecord(ENV_VARS);
