export const nextEnv = {
  NEXT_PUBLIC_CONVEX_URL: process.env.NEXT_PUBLIC_CONVEX_URL!,
  NEXT_PUBLIC_UPLOAD_SIZE_LIMIT: process.env.NEXT_PUBLIC_UPLOAD_SIZE_LIMIT!,
  NEXT_PUBLIC_STRIPE_TIER_1_PRICEID:
    process.env.NEXT_PUBLIC_STRIPE_TIER_1_PRICEID,
  NEXT_PUBLIC_STRIPE_TIER_2_PRICEID:
    process.env.NEXT_PUBLIC_STRIPE_TIER_2_PRICEID,
  NEXT_PUBLIC_STRIPE_TIER_3_PRICEID:
    process.env.NEXT_PUBLIC_STRIPE_TIER_3_PRICEID,
  NEXT_PUBLIC_STRIPE_TIER_1_CREDITS:
    process.env.NEXT_PUBLIC_STRIPE_TIER_1_CREDITS,
  NEXT_PUBLIC_STRIPE_TIER_2_CREDITS:
    process.env.NEXT_PUBLIC_STRIPE_TIER_2_CREDITS,
  NEXT_PUBLIC_STRIPE_TIER_3_CREDITS:
    process.env.NEXT_PUBLIC_STRIPE_TIER_3_CREDITS,
  AUTH_GOOGLE_ID: process.env.AUTH_GOOGLE_ID!,
  AUTH_GOOGLE_SECRET: process.env.AUTH_GOOGLE_SECRET!,
};
